import { useState, useRef } from 'react';
import { decompress, deserialize } from '../utils/huffman.js';

export default function DecompressTab({ lastCompressed }) {
  const [output, setOutput] = useState('');
  const [stats, setStats] = useState(null);
  const [error, setError] = useState('');
  const [fileInfo, setFileInfo] = useState(null);
  const [huffData, setHuffData] = useState(null);
  const fileRef = useRef();

  function loadHuffFile(e) {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      try {
        const data = deserialize(ev.target.result);
        setHuffData(data);
        setFileInfo({ name: file.name, bits: data.bits.length, chars: Object.keys(data.codes).length });
        setError('');
        setOutput('');
        setStats(null);
      } catch {
        setError('Invalid .huff file. Please use a file generated by this tool.');
      }
    };
    reader.readAsText(file);
  }

  function useLastResult() {
    if (!lastCompressed) return;
    setHuffData({ bits: lastCompressed.bits, codes: lastCompressed.codes });
    setFileInfo({ name: 'last-compressed (in memory)', bits: lastCompressed.bits.length, chars: Object.keys(lastCompressed.codes).length });
    setOutput('');
    setStats(null);
    setError('');
  }

  function handleDecompress() {
    if (!huffData) return;
    try {
      const t0 = performance.now();
      const text = decompress(huffData.bits, huffData.codes);
      const t1 = performance.now();
      setOutput(text);
      setStats({
        chars: text.length,
        bits: huffData.bits.length,
        time: (t1 - t0).toFixed(2),
      });
      setError('');
    } catch (e) {
      setError(e.message);
    }
  }

  function downloadTxt() {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'decompressed.txt';
    a.click();
  }

  return (
    <div>
      <div
        className="drop-zone"
        onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); }}
        onDragLeave={e => e.currentTarget.classList.remove('drag-over')}
        onDrop={e => {
          e.preventDefault();
          e.currentTarget.classList.remove('drag-over');
          const file = e.dataTransfer.files[0];
          if (file) loadHuffFile({ target: { files: [file] } });
        }}
        onClick={() => fileRef.current.click()}
      >
        <div className="drop-icon">🗜️</div>
        <p>Drop a <span className="accent">.huff file</span> or <span className="accent">click to browse</span></p>
        <input type="file" accept=".huff" ref={fileRef} onChange={loadHuffFile} style={{ display: 'none' }} />
      </div>

      {fileInfo && (
        <div className="alert alert-success">
          Loaded: <strong>{fileInfo.name}</strong> — {fileInfo.bits.toLocaleString()} bits, {fileInfo.chars} unique characters
        </div>
      )}

      {error && <div className="alert alert-error">{error}</div>}

      <div className="btn-row">
        <button className="btn btn-primary" onClick={handleDecompress} disabled={!huffData}>
          Decompress →
        </button>
        <button
          className="btn btn-secondary"
          onClick={useLastResult}
          disabled={!lastCompressed}
          title={!lastCompressed ? 'Compress something first' : 'Use the last compression result'}
        >
          Use last compressed
        </button>
      </div>

      {output && (
        <>
          {stats && (
            <div className="stats-grid" style={{ marginTop: '1rem' }}>
              {[
                { label: 'Chars recovered', value: stats.chars.toLocaleString(), cls: 'green' },
                { label: 'Bits decoded', value: stats.bits.toLocaleString(), cls: 'blue' },
                { label: 'Time taken', value: stats.time + ' ms', cls: 'amber' },
                { label: 'Status', value: '✓ Lossless', cls: 'green' },
              ].map(s => (
                <div className="stat-box" key={s.label}>
                  <div className="stat-label">{s.label}</div>
                  <div className={`stat-value ${s.cls}`}>{s.value}</div>
                </div>
              ))}
            </div>
          )}

          <div className="card" style={{ marginTop: '1rem' }}>
            <div className="card-title">Recovered text</div>
            <textarea
              className="text-input"
              value={output}
              readOnly
              rows={8}
              style={{ color: '#00d4aa' }}
            />
            <div className="btn-row">
              <button className="btn btn-primary" onClick={downloadTxt}>
                ⬇ Download decompressed.txt
              </button>
              <button className="btn btn-secondary" onClick={() => navigator.clipboard.writeText(output)}>
                Copy text
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
